---
#
# Unified inventory without ansible_shell_type variable.
#
all:
 vars:
   # ansible_user: root
   # ansible_password: password
 hosts:
    vm-00-d000001.zone.my.domain: # Windows host
    vm-00-d000002.zone.my.domain: # Linux host
