---
webservers:
  vars:
    server_tag: webservers
  hosts:
    foo.example.com:
    bar.example.com:
dbservers:
  vars:
    server_tag: dbservers
  hosts:
    one.example.com:
    two.example.com:
    three.example.com:
