---
- name: Set CDROM drive letter
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure variables are set
      ansible.builtin.assert:
        quiet: true
        that:
          - cdrom_letter is defined

    - name: Set CDROM drive letter
      ansible.windows.win_powershell:
        error_action: "stop"
        script: "{{ lookup('file', 'cdrom.ps1') }}"
        parameters:
          letter: "{{ cdrom_letter }}"
